baseurl = "/"
Paginate = 5

[params]
  env = "development"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Donations"
  weight = 2
  identifier = "donations"
  url = "/donations"

# datocms:start
title = "SCD Hub"
languageCode = "en"
# datocms:end
