baseurl = "/"
Paginate = 5

[params]
  env = "production"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

  name = "Donations"
  weight = 1
  identifier = "donations"
  url = "/donations"

# datocms:start
title = "SCDHub.org."
languageCode = "en"
# datocms:end
